### ISSUE TITLE
Sometimes the widget battery percentage gets stuck

### ISSUE THREAD

**Issue by MarcAnt01** [Magisk-Modules-Repo/motoclockwidget#4]
![Screenshot_Quickstep_20190527-074604](https://user-images.githubusercontent.com/43090263/58398488-7d0b9f80-8055-11e9-8a18-5a0f11c1f04c.png)

**Comment by the-dark-soldier** [comment]
Yes, I realized, unfortunately the update of the application that corrects this only works from android 8.
In a few weeks I will be launching a new version compatible only with Android 8 and 9 (This version will be available as a legacy as it will only receive updates from the installer)

**Comment by MarcAnt01** [comment]
As you seem to use Unity you can select different .apk files depending on Android version, if you are agree, I can embark a pull request for that

**Comment by the-dark-soldier** [comment]
Okay. You can do it
I leave the link of the [moto clock](https://drive.google.com/open?id=1TKQBgL4aP0tXKLiq8Csicr1458VoIACe), which only works with android 8-9

**Comment by MarcAnt01** [comment]
OK, working on it rn can you tell me minimum api level for the widget to work?

**Comment by MarcAnt01** [comment]
@dark-basic I have made a working version with the switch, I just need to know minimum api for older version and I can open a pr

**Comment by the-dark-soldier** [comment]
Minimun Api: 22 (Android 5.1) - Max: 25 (Old App) 
Minimun Api: 26 (Android 5.1) - Max: ¿Android Q?(New App)

**Comment by MarcAnt01** [comment]
OK, fixed

**Comment by MarcAnt01** [comment]
Hey, started having some force closes of Weather add-on, with new version, are you planning to re-add it again?

**Comment by the-dark-soldier** [comment]
I'll upload a new module, (As soon as I finish the exams at the university). Agradesco your help, but I think we open the Pandora's box with version 2.3

**Comment by MarcAnt01** [comment]
OK, in the meanwhile I am trying to find a solution for the exception

**Comment by MarcAnt01** [comment]
I dunno if repo would accept two similar modules, tho
